# Site settings
title: Jonathan Kirst
subtitle: Personal Blog
email: jskirst@gmail.com
description: Personal blog for Jonathan Kirst
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dev.starfighterheavyindustries.com:4000" # the base hostname & protocol for your site
author:
street_address: 3919 Cerrito Avenue
city: Oakland
state: CA
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jskirst

# Build settings
markdown: kramdown

sass:
  style: compressed
